import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

export const commitTypes = [
  'feat',
  'fix',
  'perf',
  'refactor',
  'docs',
  'test',
  'build',
  'ci',
  'chore',
  'style',
  'revert'
]
export const maxHeaderLength = 100

const headerPattern = /^(?<type>[a-z]+)(?:\((?<scope>[\w.\-/]+)\))?(?<bang>!)?: (?<subject>\S.*)$/
// Fields of `git log --format` are separated by unit / record separators, which commit
// messages cannot contain in practice.
const logFormat = '--format=%H%x1f%B%x1e'

/** Parses a Conventional Commits header; returns null when it does not match. */
export function parseCommit(message) {
  const [header, ...rest] = message.trim().split(/\r?\n/)
  const match = headerPattern.exec(header)
  if (!match || !commitTypes.includes(match.groups.type)) return null
  const body = rest.join('\n')
  return {
    type: match.groups.type,
    scope: match.groups.scope ?? null,
    subject: match.groups.subject.trim(),
    breaking: Boolean(match.groups.bang) || /^BREAKING[ -]CHANGE: /m.test(body)
  }
}

/** Removes what git strips from a message file: comment lines and everything below the scissors. */
export function cleanMessage(text) {
  const lines = []
  for (const line of text.split(/\r?\n/)) {
    if (/^# -+ >8 -+$/.test(line)) break
    if (!line.startsWith('#')) lines.push(line)
  }
  return lines.join('\n').trim()
}

/**
 * Returns the problems with a commit message (empty when it is valid). Merge and revert
 * commits generated by git are accepted; `fixup!` / `squash!` / `amend!` only with
 * `allowAutosquash`, since they must be squashed before reaching main.
 */
export function checkMessage(message, { allowAutosquash = false } = {}) {
  if (!message) return ['the commit message is empty']
  const [header, second] = message.split(/\r?\n/)
  if (/^Merge /.test(header) || /^Revert "/.test(header)) return []
  if (/^(fixup|squash|amend)! /.test(header)) {
    return allowAutosquash ? [] : [`"${header}" must be squashed before it is pushed`]
  }
  const problems = []
  const match = headerPattern.exec(header)
  if (!match) {
    problems.push(`"${header}" does not match "type(scope): subject" (scope and "!" are optional)`)
  } else if (!commitTypes.includes(match.groups.type)) {
    problems.push(`unknown type "${match.groups.type}"; use one of ${commitTypes.join(', ')}`)
  }
  if (header.length > maxHeaderLength) {
    problems.push(
      `the first line is ${header.length} characters; keep it within ${maxHeaderLength}`
    )
  }
  if (second !== undefined && second.trim() !== '') {
    problems.push('separate the first line from the body with a blank line')
  }
  return problems
}

/** Lists the commits in a git revision range (oldest first) as `{ hash, message }`. */
export function readCommits(range, cwd = process.cwd()) {
  const result = spawnSync('git', ['log', '--reverse', logFormat, range], {
    cwd,
    encoding: 'utf8',
    maxBuffer: 50 * 1024 * 1024,
    windowsHide: true
  })
  if (result.error) throw result.error
  if (result.status !== 0) throw new Error(`git log ${range} failed: ${result.stderr.trim()}`)
  return result.stdout
    .split('\x1e')
    .map((record) => record.replace(/^\r?\n/, ''))
    .filter((record) => record.includes('\x1f'))
    .map((record) => {
      const [hash, message] = record.split('\x1f')
      return { hash, message: message.trim() }
    })
}

const usage = 'Usage: node scripts/commit-msg.mjs <message-file> | --range <from>..<to>'

/** Runs the CLI and returns its exit code. */
export function main(args, cwd = process.cwd()) {
  const report = (label, problems) => {
    console.error(`✖ ${label}`)
    for (const problem of problems) console.error(`  - ${problem}`)
  }
  if (args[0] === '--range' && args[1]) {
    let failed = 0
    const commits = readCommits(args[1], cwd)
    for (const { hash, message } of commits) {
      const problems = checkMessage(message)
      if (problems.length === 0) continue
      failed++
      report(`${hash.slice(0, 7)} ${message.split(/\r?\n/)[0]}`, problems)
    }
    if (failed === 0)
      console.log(`✔ ${commits.length} commit message(s) follow Conventional Commits`)
    return failed === 0 ? 0 : 1
  }
  if (args.length !== 1 || args[0].startsWith('-')) {
    console.error(usage)
    return 2
  }
  const problems = checkMessage(cleanMessage(readFileSync(resolve(cwd, args[0]), 'utf8')), {
    allowAutosquash: true
  })
  if (problems.length === 0) return 0
  report('Commit message rejected (Conventional Commits, see CONTRIBUTING.md):', problems)
  return 1
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  process.exitCode = main(process.argv.slice(2))
}
